# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvC9i4RfIZM2en_WdDuyEldDlkzsnAlH
"""

pip install scikit-learn pandas

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# 建立簡單的資料集
data = {
    'area': [50, 60, 70, 80, 90, 100, 110, 120],      # 房屋面積 (平方公尺)
    'rooms': [1, 2, 2, 3, 3, 4, 4, 5],                 # 房間數
    'price': [500, 600, 650, 800, 850, 950, 1000, 1200]  # 價格 (萬)
}

df = pd.DataFrame(data)

# 特徵 (X) 和目標 (y)
X = df[['area', 'rooms']]
y = df['price']

# 拆分訓練與測試資料
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 建立模型並訓練
model = LinearRegression()
model.fit(X_train, y_train)

# 測試模型預測
predicted = model.predict(X_test)

# 印出測試結果
for i in range(len(X_test)):
    print(f"面積: {X_test.iloc[i]['area']} 坪，房間: {X_test.iloc[i]['rooms']} 間 → 預測價格: {round(predicted[i], 2)} 萬")

# 🧮 可以輸入新資料進行預測
new_area = 85
new_rooms = 3
new_price = model.predict([[new_area, new_rooms]])
print(f"\n🏡 預測一間 {new_area} 坪、{new_rooms} 房的房子價格：約 {round(new_price[0], 2)} 萬")